sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: haofei20
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: ml7mp3xttu7VFTh4M4NxOLOdnzy9mU
    access-key-id: LTAI5tAV5PhTrg7ZeXx9X9ij
    bucket-name: jerkoff
  wechat:
    appid: wx3262712893ad3efd
    secret: b7a76c34c9e562ebf4864186dd545dea
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
