sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: haofei20
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBE3mAkCYRHg4W1rCGm
    access-key-secret: bTqN15W3B21lDXTFBGclAMJvuk6tIv
    bucket-name: jerkoff
  redis:
    host: localhost
    port: 6379
    password:
    database: 10